version: "3.9"

services:
  web:
    build: .
    command: gunicorn crime.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DAieregMINkfVjiyAFSbcuJqkMkCAxKY

volumes:
  postgres_data:
