[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = [
  "python310",       # Compatible Python version (avoid 3.12 for OpenCV now)
  "glib",            # Required by OpenCV
  "mesa",            # Provides libGL.so.1
  "libxext",         # Correct lowercase spelling
  "libxrender",      # Correct lowercase spelling
  "libsm"            # MUST be spelled as "libSM" (case-sensitive match in Nix)
]

[variables]
PYTHON_VERSION = "3.10"

