[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = [
  "python310",
  "mesa",            # Provides libGL
  "glib",
  "libxext",         # lowercase, correct derivation
  "libxrender",
  "libsm"            # lowercase, correct derivation
]

[variables]
PYTHON_VERSION = "3.10"
